version: '3.9'
services:
  http:
      image: golang:1.17
      volumes:
        - $GOPATH/pkg/mod:/go/pkg/mod
        - ./:/src/go
      working_dir: /src/go/
      environment:
        - PORT=8080
      command: go run main.go
      ports:
        - 8080:8080
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      # - "9410:9410"
      - "9411:9411"   
    # network_mode: host 
  jaeger:
    image: jaegertracing/all-in-one
    # environment:
    #   COLLECTOR_ZIPKIN_HOST_PORT: 9412
    ports:
      - "16686:16686"   # HTTP UI
      - "14268"
      - "14250"
    # network_mode: host
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"        # Zipkin receiver
      # - "4318:4318"   # OTLP/HTTP receiver
      - "55679:55679" # zpages extension
      - "4317:4317"   # OTLP gRPC receiver
      # - "55680:55680"   # OTLP over gRPC (legacy)
      - "55681:55681"   # OTLP over HTTP (legacy)
    depends_on:
      - jaeger
      - zipkin
    # network_mode: host
